#+TITLE: Designing DFA
#+DATE: 4 February 2019
#+OPTIONS: H:4 num:nil toc:t \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t ':t |:t
#+STARTUP: showeverything entitiespretty

* Designing a DFA

  This approach to solving Exercise 5.2.4.2 is based on suggestions by Ganesh,
  which expand on the analysis/design methodology presented on pages 61 and 62
  in Chapter 5.

  The idea is to capture the \ldquo{}in your head\rdquo thoughts about state name and
  transition choices. There are P equivalence classes under the mod operation,
  where P is the modulus. A representative of each equivalence class is all that
  is needed to keep track of \ldquo{}input bits seen so far\rdquo.

** Priors
  1. Let Modulus P > 2 (P = 5 for the exercise, but let P = 3 below).
  2. Use % for mod.
  3. Use a pair of numbers for a state name.
  4. Use -b-> to indicate bit b arriving in the input.

** The ORIG series
  This is the LSB-first series (call it \ldquo{}ORIG\rdquo). After \ldquo{}modding\rdquo we
  call it \ldquo{}ALT\rdquo.

  {(2^k, N), (2^{k+1}, N+2^{k}\cdot{}b), \dots, (2^{k+2}, (N+2^{k}^{}\cdot{}b) + (b\cdot{}2^{k+1}^{}))}

  Example bits arriving LSB-first:

  :         0
  :       0 0
  :     1 0 0
  :   1 1 0 0
  : 1 1 1 0 0

  Here is ORIG line by line: it starts at the pair (1,0) where so far, yes, % 3 = 0:

  | Input bit | To Pair | So far % 3 = 0? |
  |-----------+---------+-----------------|
  | -0->      | (2,0)   | yes             |
  | -0->      | (4,0)   | yes             |
  | -1->      | (8,4)   | no              |
  | -1->      | (16,12) | yes             |
  | -1->      | (32,28) | no              |

  This goes unbounded, but we don\rsquo{}t need all that info if we just do the
  mod-based summarization of essential information.

  We only need the \ldquo{}N % P\rdquo part; thus, let\rsquo{}s apply the % operator and use its
  properties to simplify what we see:

  (N + 2^{k}\cdot{}b) % P

  = (N % P + (2^{k}\cdot{}b) % P) % P

  = (N % P + (2^k % P \cdot b % P) % P) % P

  = (N % P + 2^k % P \cdot b) % P --- why?

  Thus maintain just 2^k % P for \ldquo{}exponent so far\rdquo and N % P for \ldquo{}number so far\rdquo.

  Call them ModExp and ModNum.




**  How does ModExp evolve?

  2^k -> 2^{k+1} becomes (2^k) % P -> (2 % P \cdot 2^k % P) % P which is (2\cdot{}2^k % P) % P.

  I.e., ModExp ALWAYS goes to (2 \cdot ModExp) % P.

  Thus the ALT series becomes

  ALT: (2^k % P, N % P) -b-> ((2 \cdot (2^k % P)) % P,  (N % P + 2^k % P \cdot b) % P)

  or in more readable form

  ALT: (ModExp, ModNum) -b->  ((2 \cdot ModExp) % P, (ModNum + ModExp \cdot b) % P)

  Let\rsquo{}s calculate the ALT series for P = 3 now, line by line.

  ALT starts at (1,0), where so far, yes, % 3 = 0.

  | From pair | Input bit | Calculation               | To pair | So far % 3 = 0? |
  |-----------+-----------+---------------------------+---------+-----------------|
  | (1,0)     | -0->      | ((2\cdot{}1)%3, (0 + (1\cdot{}0))%3)) | (2,0)   | yes             |
  | (2,0)     | -0->      | ((2\cdot{}2)%3, (0 + (0\cdot{}0))%3)) | (1,0)   | yes             |
  | (1,0)     | -1->      | ((2\cdot{}1)%3, (0 + (1\cdot{}1))%3)) | (2,1)   | no              |
  | (2,1)     | -1->      | ((2\cdot{}2)%3, (1 + (2\cdot{}1))%3)) | (1,0)   | yes             |
  | (1,0)     | -1->      | (continue as before)      | (2,1)   | no              |
  
* TODO Proceed to Design the DFA Where P = 5

  | From pair | Input bit | Calculation               | To pair | So far % 3 = 0? |
  |-----------+-----------+---------------------------+---------+-----------------|
  | (1,0)     | -0->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -1->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -0->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -1->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -0->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -1->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -0->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |
  | ()        | -1->      | ((2\cdot{}1)%5, (0 + (1\cdot{}0))%5)) |         |                 |



    #+BEGIN_SRC dot :file Lb3.png
       digraph finite_state_machine {
         rankdir=LR;
         size="4"
         node [shape = circle];
         1_0 -> 2_0 [ label = "0" ]
         F -> F1 [ label = "1" ]
         F0 -> F00 [ label = "0" ]
         F0 -> F01 [ label = "1" ]
         F1 -> F10 [ label = "0" ]
         F1 -> F11 [ label = "1" ]
         F00 -> S000 [ label = "0" ]
         F00 -> S001 [ label = "1" ]
         F01 -> S010 [ label = "0" ]
         F01 -> F011 [ label = "1" ]
         F10 -> S100 [ label = "0" ]
         F10 -> F101 [ label = "1" ]
         F11 -> F110 [ label = "0" ]
         F11 -> F111 [ label = "1" ]
         S000 -> S000 [ label = "0" ]
         S000 -> S001 [ label = "1" ]
         S001 -> S010 [ label = "0" ]
         S001 -> F011 [ label = "1" ]
         S010 -> S100 [ label = "0" ]
         S010 -> F101 [ label = "1" ]
         F011 -> F110 [ label = "0" ]
         F011 -> F111 [ label = "1" ]
         S100 -> S000 [ label = "0" ]
         S100 -> S001 [ label = "1" ]
         F101 -> S010 [ label = "0" ]
         F101 -> F011 [ label = "1" ]
         F110 -> S100 [ label = "0" ]
         F110 -> F101 [ label = "1" ]
         F111 -> F110 [ label = "0" ]
         F111 -> F111 [ label = "1" ]
       }
     #+END_SRC
